POST http://localhost:3005/sign-up
Content-Type: application/json

{
  "email":"adam@gmail.com",
  "username": "adam_richard",
  "password": "Richard_567"
}

###

POST http://localhost:3005/login
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "Richard_567"
}
###

PUT http://localhost:3005/change-password
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "Richard_567",
  "newPassword": "Richard$123"
}
###

GET http://localhost:3005/audio
###

POST http://localhost:3005/audio
Content-Type: application/json

{
  "title":"The Box",
  "audio_file": "Roddy_Ricch_-_The_Box.mp3"
}

###