POST http://localhost:3005/sign-up
Content-Type: application/json

{
  "email":" ssptonystark00@gmail.com",
  "username": "adam_rich",
  "password": "Richard_567"
}

###

POST http://localhost:3005/login
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "Richard$123"
}
###

PUT http://localhost:3005/change-password
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "Richard_567",
  "newPassword": "Richard$123"
}
###

GET http://localhost:3005/audio
###

POST http://localhost:3005/audio
Content-Type: application/json

{
  "title":"Cheap Thrills",
  "artist":"Sia",
  "image_url":"sia_image",
  "audio_file": "Sia - Cheap Thrills  ft. Sean Paul.mp3"
}

###